export { instructions, Instruction } from "./instructions/base.js";

import "./instructions/C3.1 Branches, Exception generating, and System instructions/C3.1.1 Conditional branch.js";
import "./instructions/C3.1 Branches, Exception generating, and System instructions/C3.1.2 Unconditional branch (immediate).js";
import "./instructions/C3.1 Branches, Exception generating, and System instructions/C3.1.3 Unconditional branch (register).js";
import "./instructions/C3.1 Branches, Exception generating, and System instructions/C3.1.4 Exception generation and return.js";
import "./instructions/C3.1 Branches, Exception generating, and System instructions/C3.1.5 System register instructions.js";
import "./instructions/C3.1 Branches, Exception generating, and System instructions/C3.1.7 System instructions.js";
import "./instructions/C3.1 Branches, Exception generating, and System instructions/C3.1.8 Hint instructions.js";
import "./instructions/C3.1 Branches, Exception generating, and System instructions/C3.1.9 Barriers and CLREX instructions.js";
import "./instructions/C3.2 Loads and stores/C3.2.1 Load and store register.js";
import "./instructions/C3.2 Loads and stores/C3.2.3 Load and store pair.js";
import "./instructions/C3.4 Data processing - immediate/C3.4.1 Arithmetic (immediate).js";
import "./instructions/C3.4 Data processing - immediate/C3.4.2 Logical (immediate).js";
import "./instructions/C3.4 Data processing - immediate/C3.4.3 Move (wide immediate).js";
import "./instructions/C3.4 Data processing - immediate/C3.4.5 PC-relative address calculation.js";
import "./instructions/C3.4 Data processing - immediate/C3.4.6 Bitfield move.js";
import "./instructions/C3.5 Data processing - register/C3.5.1 Arithmetic (shifted register).js";
import "./instructions/C3.5 Data processing - register/C3.5.2 Arithmetic (extended register).js";
import "./instructions/C3.5 Data processing - register/C3.5.5 Logical (shifted register).js";
import "./instructions/C3.5 Data processing - register/C3.5.7 Shift (register).js";
import "./instructions/C3.5 Data processing - register/C3.5.8 Multiply and divide.js";
import "./instructions/C3.5 Data processing - register/C3.5.12 Conditional comparison.js";
